# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/crash/Desktop/Projects/Dev/multiwindow_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/crash/Desktop/Projects/Dev/multiwindow_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crash/Desktop/Projects/Dev/multiwindow_test/CMakeFiles /home/crash/Desktop/Projects/Dev/multiwindow_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crash/Desktop/Projects/Dev/multiwindow_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multi-window-test

# Build rule for target.
multi-window-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi-window-test
.PHONY : multi-window-test

# fast build rule for target.
multi-window-test/fast:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/build
.PHONY : multi-window-test/fast

gui_datarefs.o: gui_datarefs.cpp.o

.PHONY : gui_datarefs.o

# target to build an object file
gui_datarefs.cpp.o:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_datarefs.cpp.o
.PHONY : gui_datarefs.cpp.o

gui_datarefs.i: gui_datarefs.cpp.i

.PHONY : gui_datarefs.i

# target to preprocess a source file
gui_datarefs.cpp.i:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_datarefs.cpp.i
.PHONY : gui_datarefs.cpp.i

gui_datarefs.s: gui_datarefs.cpp.s

.PHONY : gui_datarefs.s

# target to generate assembly for a file
gui_datarefs.cpp.s:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_datarefs.cpp.s
.PHONY : gui_datarefs.cpp.s

gui_functions.o: gui_functions.cpp.o

.PHONY : gui_functions.o

# target to build an object file
gui_functions.cpp.o:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_functions.cpp.o
.PHONY : gui_functions.cpp.o

gui_functions.i: gui_functions.cpp.i

.PHONY : gui_functions.i

# target to preprocess a source file
gui_functions.cpp.i:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_functions.cpp.i
.PHONY : gui_functions.cpp.i

gui_functions.s: gui_functions.cpp.s

.PHONY : gui_functions.s

# target to generate assembly for a file
gui_functions.cpp.s:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/gui_functions.cpp.s
.PHONY : gui_functions.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/multi-window-test.dir/build.make CMakeFiles/multi-window-test.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... multi-window-test"
	@echo "... gui_datarefs.o"
	@echo "... gui_datarefs.i"
	@echo "... gui_datarefs.s"
	@echo "... gui_functions.o"
	@echo "... gui_functions.i"
	@echo "... gui_functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

